# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, make a package, upload the artefact to GitHub

name: Lab3 Create Artefact

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - run: npm clean-install

      - run: npm run lint

      - if: github.ref == 'refs/heads/master'
        run: npm pack

      - if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: node-todo-${{ github.sha }}
          path: ./*.tgz
